Fix race condition in logging tests (#1693)
Some of the logging tests occasionally failed because `LockedWriter`
panicked when trying to retrieve the underlying buffer. For example in
https://github.com/awslabs/mountpoint-s3/actions/runs/18838458022/job/53744837442#step:7:2151:

```
thread 'logging::syslog::tests::test_syslog_layer' panicked at mountpoint-s3-fs/src/logging/testing.rs:11:47:
called `Result::unwrap()` on an `Err` value: Mutex [..]
```

### Does this change impact existing behavior?

No.

### Does this change need a changelog entry? Does it require a version
change?

No.

---

By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license and I agree to the terms of
the [Developer Certificate of Origin
(DCO)](https://developercertificate.org/).

Signed-off-by: Alessandro Passaro <alexpax@amazon.co.uk>